const SECOND_MS = 1_000;
const MINUTE_MS = 60 * SECOND_MS;

export const SYSTEM_MODE_STALE_TIME_MS = 30 * MINUTE_MS;
export const SYSTEM_MODE_POLL_FLOOR_MS = 60 * SECOND_MS;
export const MODEL_SETUP_STALE_TIME_MS = 5 * MINUTE_MS;
export const PREFLIGHT_STALE_TIME_MS = 30 * SECOND_MS;
export const PROJECTS_STALE_TIME_MS = 30 * SECOND_MS;
export const CAPTURE_GUIDE_STALE_TIME_MS = 60 * MINUTE_MS;
export const PROJECT_ASSETS_STALE_TIME_MS = 30 * SECOND_MS;
export const ASSET_DETAIL_STALE_TIME_MS = Infinity;
export const ASSET_PROXY_AVAILABILITY_STALE_TIME_MS = 30 * SECOND_MS;
export const PROJECT_SUBJECTS_STALE_TIME_MS = 30 * SECOND_MS;
export const SUBJECT_DETAIL_STALE_TIME_MS = 30 * SECOND_MS;
export const CANONICAL_SETS_STALE_TIME_MS = 30 * SECOND_MS;
export const APPROVED_CANONICAL_SET_STALE_TIME_MS = 30 * SECOND_MS;
export const CANONICAL_REFERENCES_STALE_TIME_MS = 30 * SECOND_MS;
export const STYLE_PROFILES_STALE_TIME_MS = 30 * SECOND_MS;
export const PROJECT_PROPS_STALE_TIME_MS = 30 * SECOND_MS;
export const RENDER_JOB_STALE_TIME_MS = 5 * SECOND_MS;
export const RENDER_JOB_POLL_FLOOR_MS = 15 * SECOND_MS;

export const DEFAULT_RETRY_COUNT = 2;
