import type { JobState } from 'sky-filme-studio-be/contracts';
import type { StatusTone } from '@/lib/interfaces/status-tone';
import { STATUS_TONE } from '@/lib/status-tone.constants';

export const JOB_STATE_TONE: Record<JobState, StatusTone> = {
  PENDING: STATUS_TONE.NEUTRAL,
  CLAIMED: STATUS_TONE.CHECKING,
  PREPARING: STATUS_TONE.CHECKING,
  SUBMITTED: STATUS_TONE.ACTIVE,
  RUNNING: STATUS_TONE.PROCESSING,
  POST_PROCESSING: STATUS_TONE.PROCESSING,
  VALIDATING: STATUS_TONE.CHECKING,
  SUCCEEDED: STATUS_TONE.SUCCESS,
  FAILED_RETRYABLE: STATUS_TONE.WARNING,
  FAILED_FINAL: STATUS_TONE.DANGER,
  CANCELLED: STATUS_TONE.NEUTRAL,
  STALE: STATUS_TONE.STALE,
};
