import type { ProductionState } from 'sky-filme-studio-be/contracts';
import type { StatusTone } from '@/lib/interfaces/status-tone';
import { STATUS_TONE } from '@/lib/status-tone.constants';

export const PRODUCTION_STATE_TONE: Record<ProductionState, StatusTone> = {
  IDEA: STATUS_TONE.NEUTRAL,
  OUTLINE_DRAFT: STATUS_TONE.ACTIVE,
  OUTLINE_APPROVED: STATUS_TONE.SUCCESS,
  SCREENPLAY_DRAFT: STATUS_TONE.ACTIVE,
  SCREENPLAY_APPROVED: STATUS_TONE.SUCCESS,
  PLANNING: STATUS_TONE.ACTIVE,
  STORYBOARDING: STATUS_TONE.PROCESSING,
  STORYBOARD_REVIEW: STATUS_TONE.ATTENTION,
  AUDIO_RENDER: STATUS_TONE.PROCESSING,
  VIDEO_RENDER: STATUS_TONE.PROCESSING,
  SHOT_REVIEW: STATUS_TONE.ATTENTION,
  ASSEMBLY: STATUS_TONE.PROCESSING,
  FINAL_QC: STATUS_TONE.CHECKING,
  COMPLETE: STATUS_TONE.SUCCESS,
  ARCHIVED: STATUS_TONE.NEUTRAL,
};
