import type { ShotState } from 'sky-filme-studio-be/contracts';
import type { StatusTone } from '@/lib/interfaces/status-tone';
import { STATUS_TONE } from '@/lib/status-tone.constants';

export const SHOT_STATE_TONE: Record<ShotState, StatusTone> = {
  PLANNED: STATUS_TONE.NEUTRAL,
  STORYBOARD_PENDING: STATUS_TONE.NEUTRAL,
  STORYBOARD_READY: STATUS_TONE.READY,
  STORYBOARD_APPROVED: STATUS_TONE.SUCCESS,
  AUDIO_PENDING: STATUS_TONE.NEUTRAL,
  AUDIO_READY: STATUS_TONE.READY,
  VIDEO_PENDING: STATUS_TONE.NEUTRAL,
  VIDEO_RENDERING: STATUS_TONE.PROCESSING,
  VIDEO_READY: STATUS_TONE.READY,
  AUTO_QC: STATUS_TONE.CHECKING,
  MANUAL_REVIEW: STATUS_TONE.ATTENTION,
  APPROVED: STATUS_TONE.SUCCESS,
  REJECTED: STATUS_TONE.WARNING,
  RENDER_FAILED: STATUS_TONE.DANGER,
  ASSEMBLED: STATUS_TONE.SUCCESS,
};
